# Dockerfile.streamlit

FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt /app/
RUN apt-get update && apt-get install -y build-essential && \
    pip install --no-cache-dir -r requirements.txt

# entrypoint.sh is mounted from host, so no need to COPY here

CMD ["streamlit", "run", "/opt/airflow/Visor/dashboard.py", "--server.port", "8501", "--server.enableCORS", "false"]
