x-airflow-common:
  &airflow-common
  image: apache/airflow:2.7.2
  environment:
    &airflow-env
    AIRFLOW__CORE__EXECUTOR: CeleryExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CELERY__BROKER_URL: redis://redis:6379/0
    AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./apis:/opt/airflow/apis
    - ./requirements.txt:/requirements.txt
  user: "${AIRFLOW_UID:-50000}:${AIRFLOW_GID:-0}"
  depends_on:
    - postgres
    - redis

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest

  airflow-webserver:
    <<: *airflow-common
    command: >
      bash -c "
        pip install --no-cache-dir -r /requirements.txt &&
        airflow webserver
      "
    ports:
      - "8080:8080"
    depends_on:
      - airflow-scheduler
      - postgres
      - redis

  airflow-scheduler:
    <<: *airflow-common
    command: >
      bash -c "
        pip install --no-cache-dir -r /requirements.txt &&
        airflow scheduler
      "
    depends_on:
      - postgres
      - redis

  airflow-worker:
    <<: *airflow-common
    command: >
      bash -c "
        pip install --no-cache-dir -r /requirements.txt &&
        airflow celery worker
      "
    depends_on:
      - postgres
      - redis

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "
        pip install --no-cache-dir -r /requirements.txt &&
        airflow db migrate &&
        airflow users create --username admin --firstname Admin --lastname User --role Admin --password admin --email admin@example.com
      "
    depends_on:
      - postgres
      - redis

volumes:
  postgres-db-volume: